### ISSUE TITLE
Only support on linux?

### ISSUE THREAD

**Issue by sumai-1998** [google/navi#2]
When I run the cell " Display the multiview images, alignments, masks, and depth of the multiview scene on the fly." The error: 'FileNotFoundError: Could not find module 'libEGL.so.1' (or one of its dependencies). Try using the full path with constr......' occurs, The online solutions all refer to install [sudo apt-get install libgl1-mesa-glx], but I use Windows 10 system. Which platform did you run the project?

**Comment by kmaninis** [comment]
Hi, thank you for the interest. We indeed developed our code on Linux, so we would not expect it to work on Windows out of the box.
